# -*- coding: utf-8 -*-
"""Analysis of Football Data_GL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GhkqEYk9Q5oIToYJNLaRHZrCYLk_hK7U
"""

#Loading the required libraries
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
#the below code is used to load the csv files to google colab

from google.colab import files
uploaded = files.upload()

fifa = pd.read_csv('fifa data.csv')

fifa.head()

for col in fifa.columns:
  print(col)

fifa.shape

fifa['nationality'].value_counts()

fifa['nationality'].value_counts()[0:10]

fifa['nationality'].value_counts()[0:5]

fifa['nationality'].value_counts()[0:5].keys()

plt.figure(figsize=(8,5))
plt.bar(list(fifa['nationality'].value_counts()[0:5].keys()),list(fifa['nationality'].value_counts()[0:5]),color="b")
plt.show()

player_salary = fifa[['short_name','wage_eur']]

player_salary.head()

player_salary = player_salary.sort_values(by=['wage_eur'],ascending=False)

player_salary.head()

plt.figure(figsize=(8,5))
plt.bar(list(player_salary['short_name'])[0:5],list(player_salary['wage_eur'])[0:5],color=["blue","green","red","pink","orange"])
plt.show()

fifa['nationality']=='Germany'

#Germany
Germany=fifa[fifa['nationality']=='Germany']
Germany.head(10)

Germany.sort_values(by=['height_cm'],ascending=False).head()

Germany.sort_values(by=['weight_kg'],ascending=False).head()

Germany.sort_values(by=['wage_eur'],ascending=False).head()

Germany[['short_name','wage_eur']].sort_values(by=['wage_eur'],ascending=False).head()

#Shooting
player_shooting= fifa[['short_name','shooting']]

player_shooting.sort_values(by=['shooting'],ascending=False).head()

#defending
player_defending= fifa[['short_name','defending','nationality','club']]

player_defending.sort_values(by=['defending'],ascending=False).head()

real_madrid=fifa[fifa['club']=='Real Madrid']

real_madrid.sort_values(by=['wage_eur'],ascending=False).head()

real_madrid.sort_values(by=['shooting'],ascending=False).head()

real_madrid.sort_values(by=['defending'],ascending=False).head()

real_madrid['nationality'].value_counts()